const allPosts = [
    {
        id: 'suferinta-si-arta',
        title: 'Sufletul omului se îmbogățește prin suferință',
        category: 'reflections',
        date: '2024-06-21',
        excerpt: 'O reflecție asupra suferinței ca stihie primordială și catalizator al creației, inspirată de omagiul adus lui Chadwick Boseman și viziunile filosofice ale lui Nietzsche și Kierkegaard.',
        tags: ['reflections', 'philosophy', 'art', 'existence'],
        content: `
             <img src="images/human-soul.png" alt="The Essence of the Human Soul" style="width: 100%; max-width: 400px; display: block; margin: 0 auto 30px; border: 1px solid var(--border-color);">
             
            <p>Sufletul omului se îmbogățește prin suferință, a zis Nietzsche odată. Acum câteva zile am văzut o postare despre galeria de artă creată în onoarea lui Chadwick Boseman din Los Angeles, menită nu numai să-l comemoreze pe unul dintre cei mai iubiți actori din era noastră, ci și să promoveze viziunea artistică a tinerilor afro-americani într-o industrie ostilă și lipsită de toleranță precum Hollywood. M-a pus pe gânduri și, dintr-una în alta, am ajuns să găsesc o adevărată pletoră de astfel de monumente, expoziții și evenimente artistice organizate pentru a onora moștenirea creativă unor lideri de opinie și călăuze în diverse domenii. Suferința este o stihie primordială, un animal fără stare și fără scop, ce umblă bezmetic și răscolește întreaga ființă umană, aducând cu ea o profundă schimbare. În mijlocul acestei furtuni totuși, omul a reușit să-și confrunte limitele propriei sale existențe și să-și sculpteze haotic o nouă formă de renaștere, prin artă.</p>

            <p>O să fiu sinceră, eu nu sunt un cititor avid de filosofie, dar puținii gânditori pe care i-am trecut prin filtrul minții, emblematici desigur pentru ideologiile promovate, sunt vitali a fi menționați în scopul acestui umil articol (scris între sesiuni de învățat la chimie și biologie), fix pentru a reuși să cuprind pe cât se poate “drama” sufletului uman. Kierkegaard, cel care mănâncă melancolie pe pâine dimineața , a văzut suferința ca pe o condiție necesară autenticității. Sub semnul acestei suferințe se nasc discuții fără de care noi nu ne-am putea bucura cu adevărat de viață. De câte ori n-am fost puși, deși într-o agonie cumplită, să ne recunoaștem cu adevărat intențiile față de altcineva, deoarece ne simțeam pur și simplu sufocați de un context social în care nu eram chiar noi? Kierkegaard oferă argumentul că prin suferință, individul se apropie mai mult de o înțelegere mai profundă a sinelui - așa cum considera Kant sinceritatea ca pe o datorie morală față de cei din jur, aceeași onestitate este valabilă și către noi înșine. Întrebarea e, trebuie să suferim ca să fim sinceri și, astfel, să ne dezvoltăm emoțional și spiritual? (Kierkegaard face referință și la o legătură cu divinitatea, dar trecem peste deoarece eu n-am fost niciodată încântată de argumente religioase) Da și nu. Este imperativ să fim sinceri de la început pentru a evita suferința, normal, dar această durere resimțită nu trebuie să ne fie fatală. Dimpotrivă, cu cât ne gândim mai mult la starea pe care o simțim (și nu doar “ne gândim” sau “analizăm lucid”, pentru că raționalizarea sentimentelor nu a ajutat niciodată pe nimeni, mă uit la tine Ștefan Gheorghidiu), cu atât ne apropiem de cunoașterea deplină a sinelui. Frumusețea umanității rezidă în capacitatea noastră de a transcende lumea fizică prin intermediul apanajului de emoții deopotrivă “bune și rele”, imortalizându-le de cele mai multe ori prin artă. E ceva dulce-amar să vezi cum lumina cântărețului sau pictorului tău preferat încă se reflectă ca printr-un caleidoscop al timpului în operele lor, însuflețite chiar de publicul ce le vede.</p>

            <p>În “Așa grăit-a Zarathustra”, Nietzsche vede suferința ca pe o parte esențială a vieții, susținând ideea de “eternă reîntoarcere”’, de ciclicitate a universului; suferința, după el, trebuie acceptată și transformată într-o forță creatoare. Și dacă este vorba de o astfel de viață dusă la infinit, în care tot ce s-a întâmplat, se întâmplă și se va întâmpla vreodată va continua să se repete la nesfârșit, vorbim atunci de o nevoie de “Amor fati”, o iubire a destinului - inclusiv suferințele și hopurile peste care dăm. Fără o astfel de abordare, ne-ar fi greu să credem că nu suntem subjugați de vreun monstru intergalactic care se hrănește cu visele rele ale oamenilor. De aceea, atâta timp cât trăim, învățăm să ne obișnuim cu suferința și, mai departe, să o canalizăm către ceva ce ne hrănește sufletul, ce ne aduce pacea primordială, liniște, bucurie. De asta creăm, pentru noi, pentru speranța că totul va fi bine, și pentru trecutul plin de amintiri ce nu se vor uitate.</p>
        `
    },
    {
        id: 'plasmyrage',
        title: 'Plasmyrage: O Odă închinată sângelui',
        category: 'coding',
        date: '2025-09-17',
        excerpt: 'Un proiect personal care a început din dorința de a crea ceva tangibil cu propriile mâini. Learning tools made by students for students.',
        content: `
            <p>O Oda închinată sângelui? Plasmyrage a pornit din dorința oricărui student la medicină, care încă din prima zi se visează „mare medic", de a face ceva TANGIBIL cu propriile mâini.</p>
            
            <p>Medicina, în esență, reprezintă dedicare și ambiție. Dedicare, evident, pentru a continua drumul deja început încă de la meditațiile din liceu pentru admitere, pentru menținerea acelui mindset de „best of the best". Iar ambiția? Ei bine, de obicei se rezumă la ambiția notelor, a burselor și la dorința de a-ți zdrobi competiția. Nimic greșit cu acest spirit de gladiator academic, desigur.</p>
            
            <p>Dar la mine ambiția nu a avut niciodată vreo legătură intimă cu educația formală. Tot ce am făcut până acum a fost o necesitate — ar fi fost „incomod" să nu reușesc în ceea ce îmi propun. Dar altceva mă rodea pe dinăuntru: extracurricularele, lucrurile „în plus" pe care aș fi putut să le creez cu adevărat. Cluburi? Nu aveam destulă personalitate pentru ele. Olimpiade? Da, poate, dar doar ca să alung plictiseala care mă lovea atunci când CHIAR trebuia să muncesc pentru rezultate (OLAV nu iartă haterii Anei Karenina). Proiecte personale, însă, 100% sub controlul meu, fără reguli stricte? Oh, da. Așa s-a născut ideea: **learning tools made by students for students**. Se poate? Short answer: da, cu încăpățânare, GitHub și Gemini care te privește ironic de fiecare dată când codul refuză să ruleze.</p>
            
            <p>Consider că oricine poate învăța să codeze. Însă de la a „coda" până la a „programa" e o distanță mare, străbătută de elemente de analiză, algebră, matematică pură, guys. Nu e imposibil. Dar ce e cu adevărat dificil? Brainstorming-ul și, implicit, structurarea proiectului. Poți avea cea mai spectaculoasă idee, dacă nu știi CE să faci cu ea, tot în sertar rămâne. Plasmyrage a fost conceput ca un *baby-project*, în sensul că nu mi-aș fi imaginat vreodată să îl realizez atât de repede și nici să îmi depășească așteptările privind funcționalitatea. Era un test drive, iar eu nu aveam nici măcar carnet de condus. Ce m-a motivat să continui? Ambiția. Dar nu ambiția hrănită de aplauze și recunoaștere, ci ambiția de a-mi dovedi mie că pot. Că nimic nu e imposibil cu suficientă încăpățânare (și, indirect, cu influența unui cadru didactic pasionat de domeniul hematologiei).</p>
            
            <p>Din punct de vedere tehnic, Plasmyrage s-a construit pe câteva piloni simpli dar deloc banali: **HTML și CSS** pentru partea vizuală minimalistă, **JavaScript** pentru interactivitate, și, inevitabil, repo-ul de pe **GitHub** care a fost atât teren de joacă, cât și câmp de bătălie. Am jonglat cu structuri de date și logica aplicației până să prindă contur ceva care să nu pară doar o machetă, ci un instrument funcțional. Nu am folosit framework-uri sofisticate — intenționat. A fost mai mult despre a înțelege „scheletul" din spatele aplicației, decât despre a masca imperfecțiunile cu unelte avansate. Partea tehnică a fost, paradoxal, mai puțin despre „a scrie cod" și mai mult despre a învăța să îți păstrezi calmul când ceva aparent banal refuză să funcționeze. În concluzie, Plasmyrage nu e doar un proiect, ci un exercițiu de răbdare, disciplină și (să recunoaștem) un strop de nebunie. Nu garantez că va schimba modul în care studenții privesc medicina sau învățarea. Dar garantez că m-a schimbat pe mine. Și cred că, în fond, asta e esența oricărui demers „tangibil": nu produsul final, ci omul care devii pe parcurs.</p>
        `,
        tags: ['coding', 'javascript', 'html', 'css', 'github', 'medical-education']
    },
    {
        id: 'despre-schimbare',
        title: 'Despre Schimbare și Autenticitate',
        date: '2024-07-14',
        category: 'reflections',
        tags: ['reflections', 'philosophy', 'identity'],
        excerpt: 'Lumea în care trăim este una în care schimbarea nu este doar inevitabilă, ci și vitală pentru supraviețuire. O reflecție despre identitate, măștile pe care le purtăm și curajul de a fi autentici într-o lume în continuă transformare.',
        content: `
            <img src="images/ouroboros.png" alt="Trogoautoegocrat" style="width: 100%; max-width: 400px; display: block; margin: 0 auto 30px; border: 1px solid var(--border-color);">
            
            <p>Lumea în care trăim este una în care schimbarea nu este doar inevitabilă, ci și vitală pentru supraviețuire. Suntem martori unei ere în care valorile noastre sociale se schimbă peste noapte, la fel cum se schimbă prețul la bitcoin sau discountul de pe Shein; întrebarea "ce înseamnă să fii om" devine tot mai urgentă și mai agasantă, iar singura constantă a peisajului contemporan este fix aceastǎ metamorfozǎ amețitoare ce ne amenință identitatea.</p>
            
            <p>Ne atașăm, de când suntem mici, de idealuri și stereotipuri pe care le întâlnim în nucleul familiei: un copil nu știe de bine sau rău, la fel cum nici o furnică nu cunoaște legile ecosistemului din care face parte. Subconștientul nostru nu vede și nici nu știe ce este de fapt lumea în care noi trăim. Toate "cunoștințele" pe care le acumulăm sunt datorate realității pe care noi i-o relatăm acestui subconștient, în mod indirect, prin plăceri, frici, credințe pe care le adoptăm, cum ar fi creștinismul, sau amintiri. Totul începe de când suntem capabili să înțelegem ce ne zice mama sau tata despre orice lucru. De aici până la a ne simți acaparați de așteptările societății nu mai e mult: omul a ajuns să fie condiționat de perfecțiunea falsă. Schimbarea însă, uneori chiar a întregii identități, are potențialul de a ne salva.</p>
            
            <p>Preluând de la alții trăsături agreabile și estetice în ochii publicului, ne transformăm într-un "homo deus", dar mai trist și poate chiar mai puțin interesant decât ne-am fi imaginat. Această dorință de a ne adapta este intrinsecă prin excelență, deoarece cum altfel am putea să facem față adversităților - doar adaptându-ne în funcție de mediu. Flexibilitatea și caracterul cameleonic al omului îl transforma într-un prădător apex, situat în vârful lanțului trofic- un pericol iminent mai ales pentru semenii săi. Ceea ce va distruge specia umană nu va fi neapărat un eveniment apocaliptic (deși at this point nimic nu e prea deplasat), ci tabloul sumbru al relațiilor interumane. Some food for thought: e inutil să încercăm să fim altceva decât suntem de fapt. Încet, ne pierdem firul propriei conștiințe și propriilor gânduri, care ne-au aparținut de când ne știm, înlocuindu-le cu ale unor străini. De aceea, mulți dintre noi simțim de parcă nu aparținem unui colectiv, pentru că, conștient sau nu, ne mulăm după cum vrem să fim văzuți de alții, mai ales în liceu, unde, din nefericire, ajungem într-un punct în care suntem două persoane diferite acasă versus la școală. Sau chiar trei persoane diferite, în funcție de cât de mult vă apreciați în colectiv de pe o scară de la 1 la 10. Partea cea mai tristă este că, de cele mai multe ori, nu putem să ne dăm jos aceste măști create pentru alții, nici măcar când suntem singuri; în oglindă nu rămâne să vedem decât două găuri negre în loc de ochi, care nu mai reflectă nimic din ce era odinioară.</p>
            
            <p>Pentru cei ce simt nevoia să se schimbe constant, așa cum sunt eu, e ok. Nimeni nu știe de fapt ce face- toți încercăm să ne păstrăm echilibrul în fața lumii ce oscilează constant între idealuri, de parcă ar trebui să fim experți la cum să socializăm, cum să ne alegem facultatea, sau chiar prietenii. Societatea noastră are nevoie de autenticitate și de curajul de a spune lucrurilor pe nume, mai ales când sunt atâtea cazuri de colegi care nu reușesc să se adapteze și sunt ostracizați, de cele mai multe ori indirect. În "1984", George Orwell ne arată cǎ, în fața unui regim opresiv, curajul nu rezidă doar în acțiuni eroice, ci și în capacitatea de a ne arăta fragilitatea umană. A recunoaște că nu avem toate răspunsurile deodată și că încă nu știm exact cine suntem nu ne face slabi, ci mai umani. În fața unor schimbări vertiginoase ale societății, a permite celorlalți să ne vadă așa cum suntem este un act de profundă încredere care evidențiază solidaritatea dintre oameni. Fiecare moment de ezitare, de frica de a fi văzuți, răniți, bârfiți, luați de proşti, toate acestea sunt dovada vie a unui curaj tăcut, dar de neclintit, de a înfrunta head on necunoscutul.</p>
            
            <p>Schimbarea mi-a fost deopotrivă prieten și dușman, dar acum, curajul meu stă în abilitatea de a scrie și de a recunoaște părțile mai puțin plăcute din viața unui "adult". Nu vă uitați pe voi înșiși doar pentru a fi ținuți minte pe moment- oricum soarele va exploda, deci singurii oameni care vor conta sunteți fie voi, fie cei la care țineți cu adevărat. Cei ce vă iubesc vă văd pe voi și aleg să se uite dincolo de aparențe superficiale sau de stilul vostru vestimentar. :)</p>
        `
    },
    {
       {
    id: 'esofagul-barrett',
    title: 'Esofagul Barrett: De la Metaplazie la Adenocarcinom',
    date: '2025-10-22',
    category: 'medical',
    tags: ['histologie', 'oncologie', 'educație medicală', 'patologie'],
    excerpt: 'O incursiune educațională în transformarea malignă a esofagului - de la metaplazia benignă la adenocarcinomul invaziv. Explorăm secvența neoplazică, mecanismele moleculare și implicațiile clinice ale Esofagului Barrett.',
    content: `
        <h2>Introducere: Contextul Transformării Maligne</h2>
        
        <p>De ceva zile, tot încerc să trec prin primele cursuri de histologie și să rămân cu ceva din ele. Inevitabilă îmi va fi dezamăgirea când o să aflu că neuronii mei au degenerat în procent de 60% la prima sesiune de acum un an și, în urma acestui fapt, nu voi fi capabilă să rețin decât faptul că există FOARTE mult mov în histologie! În onoarea deschiderii primului capitol de Ross and Pawlina Histology, vin aici cu o postare puțin diferită și, hopefully, educațională. Așa cum reiese din titlul extrem de sugestiv, subiectul va fi, bineînțeles, o patologie - una de care, dacă ați fost atenți măcar la o lucrare practică de Anatomie, ar fi trebuit să auziți. Și această patologie este niciuna alta decât Esofagul Barrett.</p>
        
        <p>Esofagul Barrett reprezintă o metaplazie intestinală specializată, un proces prin care epiteliul scuamos stratificat normal al esofagului distal este înlocuit cu epiteliu columnar de tip intestinal, ca răspuns adaptativ la agresiunea cronică prin reflux gastroesofagian acid. Această transformare tisulară constituie fundamentul unei secvențe neoplazice bine definite: metaplazie, displazie de grad scăzut, displazie de grad înalt și, în final, adenocarcinom invaziv. La nivel molecular, această progresie implică acumularea succesivă de mutații în gene supresoare tumorale, în special p53 și p16, dar diagnosticul rămâne ancorat în evaluarea histopatologică microscopică. Conform Ross and Pawlina's Histology, metaplazia intestinală în Esofagul Barrett se caracterizează prin prezența celulelor caliciforme, care sunt absente în epiteliul esofagian normal, dar reprezintă markerul histologic definitiv al transformării metaplazice.</p>

        <h2>Stadiul Inițial: Când Celulele Își Păstrează Încă Bunele Maniere</h2>
        
        <p>Incepem prin a vorbi cu stadiul în care lucrurile par relativ sub control, o aparență înșelătoare, desigur, căci natura are un talent remarcabil pentru a transforma ordinea în haos celular. În forma sa inițială, Esofagul Barrett prezintă o structură relativ ordonată la microscop. Celulele sunt uniform aranjate, nucleii lor sunt mici și poziționați corect la baza celulelor, iar diviziunea celulară este minimă și limitată la zonele normale de regenerare. Această configurație benignă explică de ce riscul de progresie către cancer este foarte scăzut - sub 0.5% pe an. Din acest motiv, pacienții cu această formă necesită doar supraveghere endoscopică la intervale de trei până la cinci ani.</p>
        
        <p>Însă, precum orice poveste medicală care se respectă, lucrurile nu rămân niciodată atât de simple. Tranziția către displazia de grad scăzut marchează primul semnal de alarmă, momentul în care celulele decid că nu mai au chef sa fie basic. Nucleii celulari încep să se modifice: devin mai întunecoși, se alungesc și încep să se suprapună ușor, ca niște studenți nerăbdători sa iasa la tigara. Elementul cheie care diferențiază această etapă de stadiile mai avansate este că aceste modificări rămân limitate doar la jumătatea de jos a țesutului, iar celulele încă păstrează o anumită ordine în dezvoltarea lor - o ultimă fărâmă de decență celulară, if you will.</p>
        
        <p>Este important ca medicii să distingă această displazie reală de modificările temporare cauzate de inflamație, deoarece cele din urmă dispar după tratament intensiv cu medicamente de tip  IPP (inhibitori de pompe protonice) în timp ce displazia veritabilă persistă cu o determinare demna de apreciat. Riscul de progresie crește la 1.7-13.4% pe an, ceea ce justifică o monitorizare mai atentă sau chiar intervenție terapeutică.</p>

        <h2>Displazia de Grad Înalt: Când Lucrurile Devin Oficial Îngrijorătoare</h2>
        
        <p>Dacă displazia de grad scăzut era un semnal de avertizare mai diplomatic, displazia de grad înalt este echivalentul celular al unei alarme de incendiu. Acest stadiu reprezintă pragul critic, momentul în care transformarea malignă își pune amprenta inconfundabilă asupra țesutului. Displazia de grad înalt se caracterizează prin schimbări dramatice la nivel celular, schimbări care ar face pe orice histopatolog sa isi puna mainile in cap. Nucleii devin foarte neregulați, variind extrem în mărime și formă, ocupând din ce în ce mai mult spațiu în celulă. Aspectul lor devine mult mai întunecat și neorganizat. Caracteristica cea mai importantă a acestui stadiu este pierderea completă a ordinii normale - celulele anormale sunt haotic distribuite pe toată înălțimea țesutului, de la bază până la suprafață. Vorbim de o anarhie morfologica de importanta vitala.</p>
        
        <p>Din perspectivă moleculară, și aici intră în scenă protagonistul molecular al acestei drame, la acest nivel intervine o mutație critică în gena TP53, de care cred ca ati mai auzit la cursurile de genetica (Kudos celor care au inteles materia!)</p>
        
        <p>Această genă produce o proteină esențială numită p53, considerată "gardianul genomului" deoarece oprește sau elimină celulele cu defecte grave. În celulele normale sau în EB-ND, p53 funcțional monitorizează constant integritatea genomică; când detectează anomalii, activează căi de reparare sau elimină celulele ireparabil deteriorate. Conform studiilor moleculare detaliate, mutațiile TP53 apar în aproximativ 50-70% din cazurile de HGD(High-Grade Dysplasia) și în peste 85% din adenocarcinoamele esofagiene, dar sunt rare (<5%) în EB-ND(Non-Dysplasic) și LGD(Low-Grade Dysplasia) precoce. Studiul lui Bian et al. (2001) a demonstrat că mutațiile p53 apar predominant în tranziția de la displazie de grad scăzut la displazie de grad înalt, cu acumulare nucleară de p53 detectată prin imunohistochimie în 85% din cazurile de HGD și 71% din LGD, dar absent în leziunile metaplazice non-displazice. Aceste mutații sunt predominant de tip "missense" (substituții de aminoacizi în domeniul de legare la ADN al proteinei p53, poziții 102-292), rezultând într-o proteină aberantă, nefuncțională, care nu mai poate induce apoptoza sau opriri în ciclu – un fenomen vizualizabil imunohistochimic prin acumulare nucleară difuză și intensă de proteină p53 mutantă (stabilizată prin pierderea degradării normale mediată de MDM2). Pierderea funcției p53 permite celulelor cu aneuploidie (conținut anormal de ADN) și cu defecte severe ale reparării ADN să supraviețuiască și să prolifereze necontrolat, accelerând dramatic acumularea de noi mutații oncogenice (ERBB2, MYC, KRAS) și pierderi ale altor gene supresoare tumorale, creând instabilitatea genomică masivă caracteristică HGD și adenocarcinomului. Diferența crucială între displazia de grad înalt și cancer este integritatea membranei bazale - o barieră naturală care separă țesutul de structurile profunde. În displazia de grad înalt, celulele anormale nu au trecut inca peste această barieră, ultima linie de apărare care mai menține aparențele unei false ordini. Totuși, riscul de progresie este semnificativ, între 6.6% și 19% pe an, motiv pentru care acest diagnostic constituie o indicație clară pentru intervenție terapeutică imediată, fie prin proceduri endoscopice de ablație, fie prin chirurgie. Nu mai este momentul pentru așteptare vigilentă - este momentul pentru acțiune decisivă.</p>

        <h2>Adenocarcinomul: Finalul Logic al Unei Povești Celulare Nefericite</h2>
        
        <p>Și ajungem, inevitabil, la capitolul pe care nimeni nu-l dorește dar care trebuie discutat. Adenocarcinomul invaziv apare în momentul în care celulele anormale pătrund prin membrana bazală și invadează țesuturile profunde, marcând momentul în care toate barierele protectoare au cedat definitiv. Acest eveniment transformă o leziune care putea fi tratată prin endoscopie într-un cancer cu potențial de diseminare în organism - o tranziție care schimbă radical prognosticul și opțiunile terapeutice. Clasificarea se bazează pe cât de adânc au penetrat celulele canceroase, cu cât invazia este mai profundă, cu atât riscul de metastaze ganglionare crește, urmând o regulă matematică pe care am prefera să nu o vedem aplicată în practică: regula dublării progresive a riscului. La microscop, cancerele prezintă toate modificările severe ale displaziei de grad înalt, plus evidența clară a invaziei în țesutul conjunctiv înconjurător - tabloul complet al anarhiei celulare. Prognosticul variază considerabil în funcție de stadiul în care este diagnosticat cancerul, și aici statisticile ne oferă atât speranță, cât și motivație pentru vigilență. Pacienții cu invazie superficială, limitată la mucoasă și fără metastaze ganglionare, au o rată de supraviețuire la cinci ani de 80-90% - cifre care sunt, de fapt, destul de încurajatoare și care subliniază valoarea supravegherii regulate. În contrast, stadiile avansate cu metastaze prezintă o supraviețuire sub 20%, o statistică sumbră care subliniază importanța critică a diagnosticului precoce și a supravegherii atente a pacienților cu Esofagul Barrett.</p>

        <h2>Concluzii: Ce Ar Trebui Să Reținem Din Această Incursiune Histopatologică</h2>
        
        <p>Esofagul Barrett ilustrează perfect tensiunea fundamentală a medicinei moderne – între certitudinea pe care o căutăm și incertitudinea cu care trebuie să trăim. Fiecare biopsie spune o poveste incompletă, fiecare marker molecular adaugă context, dar și complexitate. Și în final, decizia aparține omului – patologul care privește la microscop, clinicianul care recomandă tratamentul, pacientul care alege ce risc este dispus să accepte. Cu cât înțelegem mai bine mecanismele moleculare, cu atât descoperim mai multă heterogenitate. Cunoașterea adâncă ne apropie de certitudine clinică sau ne îndepărtează de ea? Și ce facem când știința avansată generează mai multe întrebări decât răspunsuri pentru pacientul din fața noastră?</p>
    `
},
].sort((a, b) => new Date(b.date) - new Date(a.date));




